# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UrbanAnalysisPlugin
                                 A QGIS plugin
  Инструмент для расчета и анализа пространственного расположения предприятий и социальных объектов
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-17
        copyright            : (C) 2026 by Шапошникова А.С.
        email                : wmwmwm2002s@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load UrbanAnalysisPlugin class from file UrbanAnalysisPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .urban_analysis_tool import UrbanAnalysisTool
    return UrbanAnalysisTool(iface)
