# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UrbanAnalysisPluginDialog
                              A QGIS plugin
 Инструмент для расчета и анализа пространственного расположения предприятий и социальных объектов
Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                            -------------------
        begin                : 2026-03-17
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Шапошникова А.С.
        email                : wmwmwm2002s@gmail.com
***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QDialog, QMessageBox
from collections import defaultdict

from qgis.core import QgsMapLayerProxyModel, QgsProject, QgsVectorLayer, QgsFeature, QgsGeometry, QgsField, QgsSingleSymbolRenderer, QgsSymbol, QgsRendererCategory, QgsCategorizedSymbolRenderer, QgsHeatmapRenderer, QgsStyle, QgsCoordinateTransform, QgsCoordinateReferenceSystem, QgsMessageLog, Qgis
from qgis.PyQt.QtGui import QColor
from qgis.PyQt.QtCore import QMetaType
from .core_logic import UrbanAnalysisLogic


FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'urban_analysis_tool_dialog_base.ui'))


class UrbanAnalysisToolDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(UrbanAnalysisToolDialog, self).__init__(parent)
        self.setupUi(self)
        self.logic = UrbanAnalysisLogic()
        
        # Настройка фильтров для выбора слоев
        self.mComboBox_homes.setFilters(QgsMapLayerProxyModel.PointLayer | QgsMapLayerProxyModel.PolygonLayer)
        self.mComboBox_objects.setFilters(QgsMapLayerProxyModel.PointLayer | QgsMapLayerProxyModel.PolygonLayer)
        
        # Подключение сигналов
        self.button_box.accepted.connect(self.validate_and_run)
        self.button_box.rejected.connect(self.reject)
        
        # Переключение режимов
        self.comboBox_mode.currentIndexChanged.connect(self.on_mode_changed)

        # Начальные значения для параметров доступности
        self.comboBox_object_type.setCurrentIndex(0)  # Школы
        self.checkBox_use_norm_radius.setChecked(True)
        self.lineEdit_min_norm_percent.setText("95")
    
    def on_mode_changed(self, index):
        """Изменение подписей и подсказок в зависимости от режима"""
        if index == 0:  # Доступность
            self.label_objects.setText("Объекты инфраструктуры:")
            self.comboBox_object_type.setEnabled(True)
            self.lineEdit_radius.setEnabled(True)
            self.checkBox_use_norm_radius.setEnabled(True)
            self.lineEdit_min_norm_percent.setEnabled(True)
            self.checkBox_show_report.setEnabled(True)
        else:  # СЗЗ
            self.label_objects.setText("Промышленные объекты:")
            self.comboBox_object_type.setEnabled(False)
            self.lineEdit_radius.setEnabled(False)
            self.checkBox_use_norm_radius.setEnabled(False)
            self.lineEdit_min_norm_percent.setEnabled(False)
            self.checkBox_show_report.setEnabled(False)
    
    def validate_and_run(self):
        """Проверка и запуск анализа"""
        homes_layer = self.mComboBox_homes.currentLayer()
        objects_layer = self.mComboBox_objects.currentLayer()
        
        if not homes_layer or not objects_layer:
            QMessageBox.warning(
                self,
                "Ошибка",
                "Пожалуйста, выберите оба слоя!"
            )
            return

        # Проверка систем координат (должны совпадать между собой)
        if homes_layer.crs() != objects_layer.crs():
            QMessageBox.warning(
                self,
                "Несовпадение СК",
                "Слои жилой застройки и объектов инфраструктуры должны быть в одной системе координат.\n"
                "Сейчас:\n"
                f"Дома: {homes_layer.crs().authid()}\n"
                f"Объекты: {objects_layer.crs().authid()}\n"
                "Приведите их к одной СК (или переопределите СК слоям) и повторите анализ."
            )
            return

        mode = self.comboBox_mode.currentIndex()

        try:
            if mode == 0:  # Доступность
                # Определяем тип объекта по выбору пользователя
                object_type_index = self.comboBox_object_type.currentIndex()
                object_type_keys = [
                    "schools",
                    "kindergartens",
                    "clinics",
                    "pharmacies",
                    "playgrounds",
                    "transport",
                    "custom",
                ]
                object_type = object_type_keys[object_type_index] if 0 <= object_type_index < len(object_type_keys) else "schools"

                # Радиус: либо нормативный, либо пользовательский
                custom_radius = None
                if not self.checkBox_use_norm_radius.isChecked():
                    radius_text = self.lineEdit_radius.text().strip()
                    if radius_text:
                        try:
                            custom_radius = float(radius_text)
                        except ValueError:
                            QMessageBox.warning(
                                self,
                                "Ошибка ввода радиуса",
                                "Радиус должен быть числом.",
                            )
                            return

                # Минимальная норма обеспеченности домов
                min_norm_percent = 95.0
                min_norm_text = self.lineEdit_min_norm_percent.text().strip()
                if min_norm_text:
                    try:
                        min_norm_percent = float(min_norm_text)
                    except ValueError:
                        pass

                results = self.logic.calculate_accessibility(
                    homes_layer,
                    objects_layer,
                    object_type=object_type,
                    custom_radius=custom_radius,
                )

                self.create_results_layer(results, homes_layer, "accessibility")

                # Сводная статистика по проекту
                total_homes = len(results)
                good = sum(1 for r in results if r.get("accessibility_class") == "Хорошо")
                medium = sum(1 for r in results if r.get("accessibility_class") == "Удовлетворительно")
                poor = sum(1 for r in results if r.get("accessibility_class") == "Недостаточно")

                def pct(x):
                    return (float(x) / float(total_homes) * 100.0) if total_homes > 0 else 0.0

                good_pct = pct(good)
                medium_pct = pct(medium)
                poor_pct = pct(poor)

                summary_text = (
                    "📊 ОТЧЕТ ПО ДОСТУПНОСТИ\n"
                    "──────────────────────\n"
                    f"Всего домов: {total_homes}\n"
                    f"✅ Достаточно (Хорошо): {good} ({good_pct:.1f}%)\n"
                    f"⚠️ Удовлетворительно: {medium} ({medium_pct:.1f}%)\n"
                    f"❌ Недостаточно: {poor} ({poor_pct:.1f}%)\n\n"
                    f"Минимальная норма обеспеченности: {min_norm_percent:.1f}% домов с уровнем 'Хорошо'\n"
                )

                if good_pct < min_norm_percent:
                    summary_text += "\nРекомендации:\n• Доля домов с достаточной доступностью ниже нормы.\n• Рассмотрите возможность размещения дополнительных объектов инфраструктуры.\n"

                if self.checkBox_show_report.isChecked():
                    QMessageBox.information(self, "Отчет по доступности", summary_text)

                QMessageBox.information(
                    self,
                    "Готово",
                    f"Расчет доступности завершен!\nОбработано объектов: {len(results)}",
                )
            else:  # СЗЗ
                violations, szz_zones = self.logic.check_szz_violations(objects_layer, homes_layer)
                self.create_violations_layer(violations, homes_layer, objects_layer, szz_zones)

                # Отчет по СЗЗ + сводка по заводам (класс, радиус, дистанции)
                total_homes = homes_layer.featureCount()
                homes_with_viol = len({v["home_id"] for v in violations})

                by_class = {}
                for v in violations:
                    cls = v.get("class", 0)
                    by_class[cls] = by_class.get(cls, 0) + 1

                viol_by_ind = defaultdict(list)
                for v in violations:
                    viol_by_ind[v["industrial_id"]].append(v)

                lines = [
                    "📊 ОТЧЕТ ПО САНИТАРНО-ЗАЩИТНЫМ ЗОНАМ",
                    "────────────────────────────────────",
                    f"Всего домов: {total_homes}",
                    f"Дома с нарушениями СЗЗ: {homes_with_viol}",
                    f"Всего нарушений (дом-объект): {len(violations)}",
                    "",
                    "Нарушения по классам опасности:",
                ]
                for cls, cnt in sorted(by_class.items()):
                    lines.append(f"  Класс {cls}: {cnt} нарушений")

                lines.append("")
                lines.append("Заводы (промобъекты), класс, радиус СЗЗ, дистанции до домов в зоне:")
                log_tag = "Urban Analysis Tool / СЗЗ"
                max_plants_in_dialog = 30
                for idx, z in enumerate(szz_zones):
                    iid = z["industrial_id"]
                    cls = z.get("class", 0)
                    r_m = z.get("radius_m", 0)
                    vlist = viol_by_ind.get(iid, [])
                    if vlist:
                        dists = [float(v.get("distance_m", 0.0)) for v in vlist]
                        d_min, d_max = min(dists), max(dists)
                        QgsMessageLog.logMessage(
                            f"Завод FID={iid}, класс={cls}, радиус СЗЗ={r_m} м, "
                            f"нарушений={len(vlist)}, дистанции {d_min:.1f}…{d_max:.1f} м",
                            log_tag,
                            Qgis.Info,
                        )
                        if idx < max_plants_in_dialog:
                            lines.append(
                                f"  • FID {iid}: класс {cls}, радиус СЗЗ {r_m} м — "
                                f"домов в зоне: {len(vlist)}; дистанция {d_min:.1f}…{d_max:.1f} м"
                            )
                            for v in sorted(
                                vlist, key=lambda x: float(x.get("distance_m", 0.0))
                            )[:5]:
                                hid = v.get("home_id")
                                dm = float(v.get("distance_m", 0.0))
                                lines.append(f"      дом FID {hid}: {dm:.1f} м")
                            if len(vlist) > 5:
                                lines.append(f"      … ещё {len(vlist) - 5} дом(ов)")
                    else:
                        QgsMessageLog.logMessage(
                            f"Завод FID={iid}, класс={cls}, радиус СЗЗ={r_m} м — нарушений нет",
                            log_tag,
                            Qgis.Info,
                        )
                        if idx < max_plants_in_dialog:
                            lines.append(
                                f"  • FID {iid}: класс {cls}, радиус СЗЗ {r_m} м — нарушений нет"
                            )

                if len(szz_zones) > max_plants_in_dialog:
                    lines.append(
                        f"  … в диалоге показаны первые {max_plants_in_dialog} заводов; "
                        f"полный свод по всем {len(szz_zones)} — в «Журнале сообщений» (вкладка {log_tag})."
                    )

                QMessageBox.information(self, "Отчет по СЗЗ", "\n".join(lines))

                QMessageBox.information(self, "Готово", f"Проверка СЗЗ завершена!\nНайдено нарушений: {len(violations)}")
            
            self.accept()
            
        except Exception as e:
            QMessageBox.critical(
                self,
                "Ошибка выполнения",
                f"Произошла ошибка: {str(e)}"
            )
    
    def create_results_layer(self, results, source_layer, result_type):
        """Создание слоя с результатами"""
        if result_type == "accessibility":
            # Создаем слой для результатов доступности
            vl = QgsVectorLayer(
                "Point?crs=" + source_layer.crs().authid(),
                "Результаты доступности",
                "memory",
            )
            pr = vl.dataProvider()

            # Добавляем поля с нормативной информацией
            pr.addAttributes(
                [
                    QgsField("home_id", QMetaType.Int),
                    QgsField("objects_count", QMetaType.Int),
                    QgsField("norm_radius", QMetaType.Int),
                    QgsField("norm_satisfied", QMetaType.Int),
                    QgsField("accessibility_class", QMetaType.QString),
                    QgsField("coverage_percent", QMetaType.Double),
                ]
            )
            vl.updateFields()

            # Добавляем объекты
            features = []
            for res in results:
                feat = QgsFeature()
                # Берем точечную геометрию центроида, чтобы она соответствовала типу слоя Point
                geom = res.get("centroid_geom")
                if geom is None:
                    geom = res["feature"].geometry()
                feat.setGeometry(geom)
                feat.setAttributes(
                    [
                        res.get("home_id"),
                        res.get("count"),
                        int(res.get("norm_radius", 0)),
                        int(res.get("norm_satisfied", 0)),
                        res.get("accessibility_class", ""),
                        float(res.get("coverage_percent", 0.0)),
                    ]
                )
                features.append(feat)

            pr.addFeatures(features)
            vl.updateExtents()

            QgsProject.instance().addMapLayer(vl)

            # Классифицированная символика по accessibility_class
            categories = []

            # Хорошо (зеленый)
            symbol_good = QgsSymbol.defaultSymbol(vl.geometryType())
            symbol_good.setColor(QColor(0, 170, 0))
            categories.append(
                QgsRendererCategory(
                    "Хорошо",
                    symbol_good,
                    "Хорошо (норма выполнена)",
                )
            )

            # Удовлетворительно (желтый)
            symbol_medium = QgsSymbol.defaultSymbol(vl.geometryType())
            symbol_medium.setColor(QColor(255, 215, 0))
            categories.append(
                QgsRendererCategory(
                    "Удовлетворительно",
                    symbol_medium,
                    "Удовлетворительно",
                )
            )

            # Недостаточно (красный)
            symbol_poor = QgsSymbol.defaultSymbol(vl.geometryType())
            symbol_poor.setColor(QColor(255, 0, 0))
            categories.append(
                QgsRendererCategory(
                    "Недостаточно",
                    symbol_poor,
                    "Недостаточно",
                )
            )

            renderer = QgsCategorizedSymbolRenderer("accessibility_class", categories)
            vl.setRenderer(renderer)
            vl.triggerRepaint()
    
    def create_violations_layer(self, violations, homes_layer, industrial_layer, szz_zones):
        """Создание слоя нарушений СЗЗ и полигонального слоя СЗЗ"""
        # Полигональный слой СЗЗ: как у расчёта доступности — расстояние в метрах через
        # QgsDistanceArea; здесь круг в метрах только в EPSG:3857 (единицы = метры).
        # Нельзя буферить полигон завода целиком — только центроид (тот же, что в
        # check_szz_violations для measureLine), иначе зона раздувается до размера контура.
        source_crs = industrial_layer.crs()
        target_crs = QgsCoordinateReferenceSystem("EPSG:3857")
        xform = QgsCoordinateTransform(source_crs, target_crs, QgsProject.instance())

        szz_layer = QgsVectorLayer("Polygon?crs=" + target_crs.authid(),
                                   "Санитарно-защитные зоны", "memory")
        szz_pr = szz_layer.dataProvider()
        szz_pr.addAttributes([
            QgsField("industrial_id", QMetaType.Int),
            QgsField("szz_class", QMetaType.Int),
            QgsField("radius_m", QMetaType.Int),
        ])
        szz_layer.updateFields()

        szz_features = []
        for zone in szz_zones:
            feat = QgsFeature()
            center = zone.get("center_geom")
            if center is None or center.isEmpty():
                g = zone["industrial_feature"].geometry()
                center = g.centroid() if not g.isEmpty() else g
            geom = QgsGeometry(center)
            geom.transform(xform)
            radius_m = float(zone["radius_m"])
            buffer_geom = geom.buffer(radius_m, 32)
            feat.setGeometry(buffer_geom)
            feat.setAttributes([
                zone["industrial_id"],
                zone["class"],
                zone["radius_m"],
            ])
            szz_features.append(feat)

        szz_pr.addFeatures(szz_features)
        szz_layer.updateExtents()

        # Стилизация СЗЗ: полупрозрачная заливка, чтобы не закрывать точки
        szz_symbol = QgsSymbol.defaultSymbol(szz_layer.geometryType())
        fill_color = QColor(255, 0, 0, 80)  # красный, полупрозрачный
        szz_symbol.setColor(fill_color)
        szz_renderer = QgsSingleSymbolRenderer(szz_symbol)
        szz_layer.setRenderer(szz_renderer)
        QgsProject.instance().addMapLayer(szz_layer)

        # Точечный слой домов-нарушителей (добавляем поверх буферов)
        vl = QgsVectorLayer("Point?crs=" + homes_layer.crs().authid(),
                            "Нарушения СЗЗ", "memory")
        pr = vl.dataProvider()

        pr.addAttributes([
            QgsField("home_id", QMetaType.Int),
            QgsField("industrial_id", QMetaType.Int),
            QgsField("szz_class", QMetaType.Int),
            QgsField("radius_m", QMetaType.Int)
        ])
        vl.updateFields()

        features = []
        for viol in violations:
            feat = QgsFeature()
            # Используем центроид геометрии дома, чтобы он гарантированно был точкой
            home_geom = viol["home_feature"].geometry()
            centroid = home_geom.centroid()
            feat.setGeometry(centroid)
            feat.setAttributes([
                viol["home_id"],
                viol["industrial_id"],
                viol["class"],
                viol["radius"],
            ])
            features.append(feat)

        pr.addFeatures(features)
        vl.updateExtents()
        QgsProject.instance().addMapLayer(vl)

        symbol = QgsSymbol.defaultSymbol(vl.geometryType())
        symbol.setColor(QColor(255, 0, 0))  # Красный
        renderer = QgsSingleSymbolRenderer(symbol)
        vl.setRenderer(renderer)
        vl.triggerRepaint()
